use std::panic::{catch_unwind, AssertUnwindSafe};
use std::time::Duration;

use lite_encoder::codec::h264::{annexb, decoder::Frontend};

const CAMERA_FIXTURE: &[u8] = include_bytes!("fixtures/tapo-1080p-cabac-8x8.h264");
const MULTISLICE_FIXTURE: &[u8] = include_bytes!("fixtures/openh264-256x128-cabac-2slice.h264");

fn fingerprint(bytes: &[u8]) -> u64 {
    bytes.iter().fold(0xcbf2_9ce4_8422_2325, |hash, byte| {
        (hash ^ u64::from(*byte)).wrapping_mul(0x0000_0100_0000_01b3)
    })
}

fn first_slice_header_offset(access_unit: &[u8]) -> usize {
    let nal = annexb::nal_units(access_unit)
        .find(|nal| matches!(nal.first().map(|header| header & 0x1f), Some(1 | 5)))
        .expect("access unit has no slice");
    nal.as_ptr() as usize - access_unit.as_ptr() as usize
}

fn initialized_decoder() -> Frontend {
    let mut decoder = Frontend::new();
    let idr = annexb::access_units(CAMERA_FIXTURE)[0];
    let frames = decoder
        .decode_access_unit(idr, Duration::ZERO)
        .expect("fixture IDR must decode");
    assert_eq!(frames.len(), 1);
    decoder
}

/// Multi-slice assembly is shipping decoder behavior, so it must run without
/// the optional C reference decoder. The fixture was generated by OpenH264
/// and its pixel fingerprints were locked after bit-exact differential decode.
#[test]
fn two_slice_pictures_decode_in_default_ci() {
    let access_units = annexb::access_units(MULTISLICE_FIXTURE);
    assert_eq!(access_units.len(), 3, "fixture picture count changed");

    let mut decoder = Frontend::new();
    let mut frames = Vec::new();
    for (index, access_unit) in access_units.into_iter().enumerate() {
        let slice_count = annexb::nal_units(access_unit)
            .filter(|nal| matches!(nal.first().map(|header| header & 0x1f), Some(1 | 5)))
            .count();
        assert_eq!(
            slice_count, 2,
            "picture {index} is not split into two slices"
        );
        frames.extend(
            decoder
                .decode_access_unit(access_unit, Duration::from_millis(index as u64 * 40))
                .unwrap_or_else(|error| panic!("picture {index} failed to decode: {error}")),
        );
    }

    assert_eq!(frames.len(), 3);
    for (index, frame) in frames.iter().enumerate() {
        assert_eq!((frame.width, frame.height), (256, 128));
        assert_eq!(frame.pts, Duration::from_millis(index as u64 * 40));
    }
    let fingerprints: Vec<[u64; 3]> = frames
        .iter()
        .map(|frame| frame.planes.each_ref().map(|plane| fingerprint(plane)))
        .collect();
    assert_eq!(
        fingerprints,
        [
            [
                0xd08a_6ece_8d66_b350,
                0xa843_9b92_520e_6e27,
                0xee92_9793_97ad_0890
            ],
            [
                0xc40b_7f76_99b9_c0b8,
                0x1bc1_d5f8_702a_8a4c,
                0xc8b8_3419_8166_b1f2
            ],
            [
                0xc049_ba48_26e1_e7aa,
                0x556a_3898_f91d_cee5,
                0x0190_2265_4642_c059
            ],
        ],
        "decoded pixels changed"
    );
}

/// Proves the default-CI fingerprints above describe the reference decoder's
/// exact output rather than merely freezing a subject-decoder bug.
#[cfg(feature = "reference-decoder")]
#[test]
fn two_slice_fixture_matches_openh264_bit_exactly() {
    use lite_encoder::codec::h264::differential;

    let report = differential::compare(MULTISLICE_FIXTURE, &mut Frontend::new())
        .expect("compare multi-slice fixture");
    assert_eq!(report.reference_frames, 3);
    assert_eq!(report.subject_frames, 3);
    assert!(report.matches(), "{report}");
}

/// Packet loss can truncate a slice at any byte. Decoder must reject it rather
/// than panic or return a partly reconstructed picture as valid output.
#[test]
fn truncated_camera_slices_fail_without_panicking_or_emitting_a_frame() {
    let access_unit = annexb::access_units(CAMERA_FIXTURE)[0];
    // The fixture has one Annex B trailing-zero byte, which is padding rather
    // than slice data and deliberately has no effect when removed.
    for removed in [2, 8, 32, 256, 1024] {
        let truncated = &access_unit[..access_unit.len() - removed];
        let outcome = catch_unwind(AssertUnwindSafe(|| {
            Frontend::new().decode_access_unit(truncated, Duration::ZERO)
        }));
        let decoded = outcome.unwrap_or_else(|_| panic!("panicked after removing {removed} bytes"));
        assert!(
            decoded.is_err(),
            "accepted a slice truncated by {removed} bytes"
        );
    }
}

/// Packet loss after decoding has begun must fail just as loudly as damage to
/// the initial IDR, without returning a partly reconstructed P picture.
#[test]
fn truncated_p_slice_fails_without_panicking_or_emitting_a_frame() {
    let p_access_unit = annexb::access_units(CAMERA_FIXTURE)[1];
    for removed in [2, 8, 32, 128] {
        let truncated = &p_access_unit[..p_access_unit.len() - removed];
        let outcome = catch_unwind(AssertUnwindSafe(|| {
            initialized_decoder().decode_access_unit(truncated, Duration::from_millis(40))
        }));
        let decoded = outcome.unwrap_or_else(|_| {
            panic!("panicked after removing {removed} bytes from a P access unit")
        });
        assert!(
            decoded.is_err(),
            "accepted a P slice truncated by {removed} bytes"
        );
    }
}

#[test]
fn corrupted_nal_header_is_rejected_without_panicking() {
    let mut corrupted = annexb::access_units(CAMERA_FIXTURE)[1].to_vec();
    let header = first_slice_header_offset(&corrupted);
    corrupted[header] |= 0x80;

    let outcome = catch_unwind(AssertUnwindSafe(|| {
        initialized_decoder().decode_access_unit(&corrupted, Duration::from_millis(40))
    }));
    let decoded = outcome.expect("corrupted NAL header caused a panic");
    let error = decoded.expect_err("corrupted NAL header emitted a frame");
    assert!(error.to_string().contains("invalid NAL header"), "{error}");
}

#[test]
fn known_invalid_cabac_bit_flips_fail_without_panicking_or_emitting_a_frame() {
    let access_units = annexb::access_units(MULTISLICE_FIXTURE);
    let access_unit = access_units[1];
    let header = first_slice_header_offset(access_unit);

    // These are CABAC-body bytes, after this slice's header and alignment.
    // Arbitrary H.264 bit flips are not universally detectable (the format
    // has no elementary-stream checksum), so lock several mutations that do
    // violate the arithmetic-coded syntax and must take the checked error path.
    for (relative, bit) in [(6, 0x02), (6, 0x08), (7, 0x01), (8, 0x01)] {
        let mut corrupted = access_unit.to_vec();
        corrupted[header + relative] ^= bit;
        let outcome = catch_unwind(AssertUnwindSafe(|| {
            let mut decoder = Frontend::new();
            decoder
                .decode_access_unit(access_units[0], Duration::ZERO)
                .expect("fixture IDR must decode");
            decoder.decode_access_unit(&corrupted, Duration::from_millis(40))
        }));
        let decoded = outcome.unwrap_or_else(|_| {
            panic!("CABAC corruption at byte {relative}, bit {bit:#04x} caused a panic")
        });
        assert!(
            decoded.is_err(),
            "CABAC corruption at byte {relative}, bit {bit:#04x} emitted a frame"
        );
    }
}

#[test]
fn p_slice_with_an_empty_dpb_is_rejected_without_panicking() {
    let access_units = annexb::access_units(CAMERA_FIXTURE);
    let mut decoder = Frontend::new();
    let slices = decoder
        .parse_access_unit(access_units[0])
        .expect("register parameter sets");
    assert!(!slices.is_empty(), "fixture IDR slice missing");

    let outcome = catch_unwind(AssertUnwindSafe(|| {
        decoder.decode_access_unit(access_units[1], Duration::from_millis(40))
    }));
    let decoded = outcome.expect("P slice with an empty DPB caused a panic");
    let error = decoded.expect_err("P slice with an empty DPB emitted a frame");
    assert!(
        error.to_string().contains("missing PicNum") || error.to_string().contains("reference"),
        "{error}"
    );
}
